[package]
name = "spidy"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = [
  "rustls",
  "json",
], default-features = false }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
eyre = "0.6"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive", "env"] }
serde_json = "1"
constcat = "0.6"
curl = "0.4"
parse-size = "1"
